language: objective-c
xcode_workspace: "APIClient.xcworkspace"
xcode_scheme: "APIClient"
before_install:
  - "brew update"
  - "brew upgrade xctool"
rvm: 1.9.3
cache: bundler
script: "bundle exec rake"
